/**
 * Rich demo content for EventwithEase — imported by seedDemoEvents.js
 * Images: Unsplash (hotlink OK for demos)
 */

export const demoOrganiser = {
  name: "Priya Menon",
  email: "demo.organiser@eventwithease.com",
  password: "demo1234",
  role: "organiser",
  roles: ["organiser", "attendee"],
  hostTagline: "Producer · conferences & product summits · Bengaluru",
  hostBio:
    "Priya programmes flagship conferences and leadership summits across India—tight run-of-show, sponsor-ready layouts, and attendee journeys that feel calm from doors to close.",
  linkedinUrl: "https://linkedin.com/in/example-priya-menon",
  twitterUrl: "https://x.com",
  instagramUrl: "https://instagram.com",
  websiteUrl: "https://eventwithease.com",
};

export const demoAttendee = {
  name: "Rohan Verma",
  email: "demo.attendee@eventwithease.com",
  password: "demo1234",
  role: "attendee",
};

/** Extra users: reviews, bookings, networking demos */
export const crowdUsers = [
  { name: "Aarav Sharma", email: "crowd.aarav@eventwithease.com", linkedinUrl: "https://linkedin.com/in/example-aarav" },
  { name: "Diya Kapoor", email: "crowd.diya@eventwithease.com", linkedinUrl: "https://linkedin.com/in/example-diya" },
  { name: "Kabir Mehta", email: "crowd.kabir@eventwithease.com", linkedinUrl: "https://linkedin.com/in/example-kabir" },
  { name: "Neha Krishnan", email: "crowd.neha@eventwithease.com", linkedinUrl: "https://linkedin.com/in/example-neha" },
  { name: "Vikram Desai", email: "crowd.vikram@eventwithease.com", networkingOptIn: false },
  { name: "Ishita Rao", email: "crowd.ishita@eventwithease.com", linkedinUrl: "https://linkedin.com/in/example-ishita" },
  { name: "Arjun Nair", email: "crowd.arjun@eventwithease.com", linkedinUrl: "https://linkedin.com/in/example-arjun" },
  { name: "Meera Joshi", email: "crowd.meera@eventwithease.com" },
  { name: "Siddharth Pillai", email: "crowd.sid@eventwithease.com", linkedinUrl: "https://linkedin.com/in/example-sid" },
  { name: "Tara Menon", email: "crowd.tara@eventwithease.com", linkedinUrl: "https://linkedin.com/in/example-tara" },
  { name: "Karan Bhatt", email: "crowd.karan@eventwithease.com" },
  { name: "Ananya Sen", email: "crowd.ananya@eventwithease.com", linkedinUrl: "https://linkedin.com/in/example-ananya" },
  { name: "Dev Malhotra", email: "crowd.dev@eventwithease.com", linkedinUrl: "https://linkedin.com/in/example-dev" },
  { name: "Priya Kulkarni", email: "crowd.priya@eventwithease.com" },
  { name: "Yash Thakur", email: "crowd.yash@eventwithease.com", linkedinUrl: "https://linkedin.com/in/example-yash" },
];

const u = (id) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=82`;

export const demoEvents = [
  // —— Past (reviews + feedback) ——
  {
    title: "Mumbai Audio & Light Expo 2025",
    description:
      "Trade floor for pro audio, stage lighting, and live-sound engineers. Brand demos, listening rooms, and a closing panel with touring crews.",
    location: "NESCO Centre, Goregaon, Mumbai",
    city: "Mumbai",
    venueType: "physical",
    category: "Music",
    date: "2025-09-14T10:00:00.000Z",
    coverImage: u("photo-1470229722913-7c0e2dbbafd3"),
    agenda: ["10:00 Trade floor opens", "13:30 Line-array shootout", "16:00 Touring life Q&A", "18:00 Networking"],
    speakers: ["Riya Sound Labs", "TourCraft India", "Priya Menon"],
    faq: [
      { question: "Parking?", answer: "Paid parking at the venue; EV charging on level B1." },
      { question: "Badges?", answer: "Digital QR on your phone is enough at entry." },
    ],
    venueMapUrl: "https://maps.google.com/?q=NESCO+Centre+Mumbai",
    discountCodes: [{ code: "AUDIO15", type: "percent", value: 15, expiresAt: "2025-09-01" }],
    ticketTypes: [
      { name: "Trade pass", price: 799, quantity: 400 },
      { name: "Pro + lounge", price: 1899, quantity: 80 },
    ],
  },
  {
    title: "Delhi Marathon Expo 2025",
    description:
      "Kit pickup, pacing clinics, and sports-tech stalls ahead of race weekend. Free gait analysis slots for the first 200 runners.",
    location: "Pragati Maidan, New Delhi",
    city: "Delhi",
    venueType: "physical",
    category: "Sports",
    date: "2025-10-18T09:00:00.000Z",
    coverImage: u("photo-1461896836934-ffe607ba8211"),
    agenda: ["09:00 Expo opens", "11:00 Pacing workshop", "14:00 Nutrition talk", "19:00 Close"],
    speakers: ["Coach Meera", "SportsMed Delhi"],
    faq: [{ question: "Can I collect for a friend?", answer: "Yes with their QR and signed authorization." }],
    venueMapUrl: "https://maps.google.com/?q=Pragati+Maidan",
    ticketTypes: [{ name: "Expo entry", price: 0, quantity: 5000 }, { name: "Clinic add-on", price: 299, quantity: 200 }],
  },
  {
    title: "Hyderabad AI Builders Night 2025",
    description:
      "Lightning talks on RAG, evals, and shipping LLM features in prod. Pizza, stickers, and a mini hack corner until midnight.",
    location: "IIIT Hyderabad Campus",
    city: "Hyderabad",
    venueType: "physical",
    category: "Tech",
    date: "2025-11-08T17:00:00.000Z",
    coverImage: u("photo-1540575467063-178a50c2df87"),
    agenda: ["17:30 Check-in", "18:15 Talks block 1", "20:00 Break", "20:30 Talks block 2", "22:00 Open hacking"],
    speakers: ["Tensor South", "LLM Bangalore", "Guest Mentor"],
    faq: [{ question: "Laptop required?", answer: "Optional for the hack corner; talks are listen-only friendly." }],
    venueMapUrl: "https://maps.google.com/?q=IIIT+Hyderabad",
    discountCodes: [{ code: "BUILD20", type: "percent", value: 20, expiresAt: "2025-11-01" }],
    ticketTypes: [
      { name: "General", price: 0, quantity: 300 },
      { name: "Supporter", price: 499, earlyBirdPrice: 349, earlyBirdEndsAt: "2025-11-01", quantity: 120 },
    ],
  },
  {
    title: "Pune Design Weekender 2025",
    description:
      "Two days of product design sprints, critique circles, and a hiring lounge with startups hiring IC and lead designers.",
    location: "Pune Marriott City Centre",
    city: "Pune",
    venueType: "physical",
    category: "Workshop",
    date: "2025-12-06T09:30:00.000Z",
    coverImage: u("photo-1542744173-8e7e53415bb0"),
    agenda: ["Day 1 — Systems & tokens", "Day 2 — Critique + portfolio reviews"],
    speakers: ["Studio North", "Pixel Pune"],
    faq: [{ question: "Portfolio review slots?", answer: "Book on arrival; first-come while slots last." }],
    venueMapUrl: "https://maps.google.com/?q=Pune+Marriott+City+Centre",
    ticketTypes: [
      { name: "2-day pass", price: 2499, earlyBirdPrice: 1999, earlyBirdEndsAt: "2025-11-25", quantity: 150 },
      { name: "Student", price: 999, quantity: 60 },
    ],
  },
  {
    title: "Chennai Indie Film Showcase 2025",
    description:
      "Regional shorts, director Q&As, and a distributor roundtable. Subtitled screenings in two screens all evening.",
    location: "SPI Cinemas Palazzo, Chennai",
    city: "Chennai",
    venueType: "physical",
    category: "Art",
    date: "2025-11-22T16:00:00.000Z",
    coverImage: u("photo-1485846234645-a62644f84728"),
    agenda: ["16:00 Block A", "18:30 Block B", "21:00 Director panel"],
    speakers: ["Chennai Film Collective"],
    faq: [{ question: "Age rating?", answer: "Most films are U/A; one A-rated block after 21:00." }],
    venueMapUrl: "https://maps.google.com/?q=SPI+Palazzo+Chennai",
    ticketTypes: [
      { name: "Standard", price: 449, quantity: 220 },
      { name: "All-access", price: 899, quantity: 80 },
    ],
  },
  {
    title: "Goa Beach Startup Brunch 2025",
    description:
      "Founders and angels over sun, surf, and serious coffee. Off-the-record AMA and speed intros on the deck.",
    location: "Anjuna North Goa (beach club)",
    city: "Goa",
    venueType: "physical",
    category: "Business",
    date: "2025-12-15T11:00:00.000Z",
    coverImage: u("photo-1507525428034-b723cf961d3e"),
    agenda: ["11:00 Brunch", "12:30 Founder stories", "14:00 Investor rotations"],
    speakers: ["Coastal Capital", "Solo GP Circle"],
    faq: [{ question: "Dress code?", answer: "Smart casual; sandals OK." }],
    venueMapUrl: "https://maps.google.com/?q=Anjuna+Goa",
    ticketTypes: [{ name: "Founder", price: 1999, quantity: 70 }, { name: "Investor", price: 1999, quantity: 40 }],
  },
  {
    title: "Kolkata Winter Street Food Fest 2025",
    description:
      "Fifty stalls, live folk fusion, and a family zone. RFID wallets for quick payments and shorter queues.",
    location: "Eco Park, New Town, Kolkata",
    city: "Kolkata",
    venueType: "physical",
    category: "Community",
    date: "2025-12-20T14:00:00.000Z",
    coverImage: u("photo-1555939594-58d7cb561ad1"),
    agenda: ["14:00 Gates", "16:00 Chef throwdown", "19:00 Headliner", "22:00 Close"],
    speakers: ["Eat Street Kolkata"],
    faq: [{ question: "Veg only stalls?", answer: "Marked green on the map; majority are mixed." }],
    venueMapUrl: "https://maps.google.com/?q=Eco+Park+Kolkata",
    ticketTypes: [{ name: "Entry", price: 199, quantity: 8000 }, { name: "Fast lane", price: 399, quantity: 500 }],
  },
  {
    title: "Bengaluru Product Leadership Summit 2025",
    description:
      "VP/CPO track on roadmaps, AI product ethics, and org design. Chatham-style sessions under NDA.",
    location: "Sheraton Grand Bengaluru",
    city: "Bengaluru",
    venueType: "physical",
    category: "Business",
    date: "2025-11-29T09:00:00.000Z",
    coverImage: u("photo-1544531586-fde5298cdd40"),
    agenda: ["09:00 Breakfast roundtables", "11:00 Keynotes", "14:00 Breakouts", "17:00 Closing"],
    speakers: ["BPL Circle", "SaaS India Guild"],
    faq: [{ question: "NDA?", answer: "You'll sign a one-page mutual NDA at check-in." }],
    venueMapUrl: "https://maps.google.com/?q=Sheraton+Grand+Bengaluru",
    ticketTypes: [{ name: "Leader pass", price: 4999, quantity: 120 }, { name: "Emerging lead", price: 2999, quantity: 60 }],
  },
  {
    title: "Bengaluru Writers Salon 2025",
    description:
      "Evening readings, craft-of-editing breakout, and a quiet networking tea for authors, editors, and newsletter-first founders.",
    location: "Church Street Social Library Room, Bengaluru",
    city: "Bengaluru",
    venueType: "physical",
    category: "Community",
    date: "2025-10-04T17:00:00.000Z",
    coverImage: u("photo-1456513080510-7bf3a84b82f8"),
    agenda: ["17:00 Doors", "17:30 Open mic", "19:00 Guest reader", "20:30 Mingle"],
    speakers: ["Lit Bangalore", "Priya Menon"],
    faq: [{ question: "Bring drafts?", answer: "Optional; sign-up sheet at the door for 5-minute slots." }],
    venueMapUrl: "https://maps.google.com/?q=Church+Street+Social+Bengaluru",
    ticketTypes: [{ name: "Salon seat", price: 349, quantity: 90 }, { name: "Patron", price: 799, quantity: 25 }],
  },
  {
    title: "Mumbai Comedy Store Night 2025",
    description:
      "Curated stand-up hour plus improv jam with rotating Mumbai open-micers and one touring headliner.",
    location: "Lower Parel Comedy Cellar, Mumbai",
    city: "Mumbai",
    venueType: "physical",
    category: "Community",
    date: "2025-10-25T20:00:00.000Z",
    coverImage: u("photo-1503095396549-807759245b35"),
    agenda: ["20:00 Doors", "20:30 Support acts", "21:30 Headliner", "22:45 Close"],
    speakers: ["Rahul Iyer", "Bombay Mic Club"],
    faq: [{ question: "Age limit?", answer: "18+ after 21:00; earlier slot is all ages." }],
    venueMapUrl: "https://maps.google.com/?q=Lower+Parel+Mumbai",
    ticketTypes: [{ name: "General", price: 599, quantity: 200 }, { name: "Front row", price: 999, quantity: 40 }],
  },
  {
    title: "Hyderabad Design Critique 2025",
    description:
      "Portfolio desk reviews with senior IC designers from product companies — bring Figma links and a thick skin.",
    location: "T-Hub Phase 2, Hyderabad",
    city: "Hyderabad",
    venueType: "physical",
    category: "Workshop",
    date: "2025-11-02T14:00:00.000Z",
    coverImage: u("photo-1581291518857-4e27b48ff24e"),
    agenda: ["14:00 Check-in", "14:30 Rotations", "18:00 Group critique", "19:00 Close"],
    speakers: ["Simran Khanna", "Pixel South"],
    faq: [{ question: "Laptop?", answer: "Yes; reviewers will annotate live." }],
    venueMapUrl: "https://maps.google.com/?q=T-Hub+Hyderabad",
    ticketTypes: [{ name: "Participant", price: 799, quantity: 70 }, { name: "Observer", price: 299, quantity: 40 }],
  },
  {
    title: "Kochi Sunsets Acoustic 2025",
    description:
      "Rooftop unplugged set with Kerala-rooted originals, tabla brushes, and single-mic storytelling between songs.",
    location: "Fort Kochi Rooftop Arts, Kochi",
    city: "Kochi",
    venueType: "physical",
    category: "Music",
    date: "2025-11-16T18:00:00.000Z",
    coverImage: u("photo-1511379938547-c1f69419868d"),
    agenda: ["18:00 Doors", "18:45 Set 1", "20:00 Set 2", "21:15 Close"],
    speakers: ["Meera Patel", "Coastal Strings"],
    faq: [{ question: "Seating?", answer: "Low stools + some floor cushions; arrive early for front." }],
    venueMapUrl: "https://maps.google.com/?q=Fort+Kochi",
    ticketTypes: [{ name: "Standard", price: 649, quantity: 120 }, { name: "Balcony", price: 1099, quantity: 35 }],
  },
  {
    title: "Jaipur Photo Walk 2025",
    description:
      "Golden hour in the Pink City bazaars with mentor loops on composition and street ethics; small group cap.",
    location: "Hawa Mahal East Gate, Jaipur",
    city: "Jaipur",
    venueType: "physical",
    category: "Art",
    date: "2025-11-30T06:30:00.000Z",
    coverImage: u("photo-1469474968028-56623f02e42e"),
    agenda: ["06:30 Meet", "07:00 Walk block 1", "08:30 Chai debrief", "09:30 Wrap"],
    speakers: ["Arjun Natesan", "Desert Frame Club"],
    faq: [{ question: "Gear?", answer: "Phone OK; DSLR renters available on-site (limited)." }],
    venueMapUrl: "https://maps.google.com/?q=Hawa+Mahal+Jaipur",
    ticketTypes: [{ name: "Walk pass", price: 499, quantity: 28 }, { name: "Walk + review", price: 899, quantity: 12 }],
  },
  {
    title: "Kolkata Indie Book Fair 2025",
    description:
      "Regional presses, zine tables, and author signings in a single hall — Bengali and English stacks side by side.",
    location: "Oxford Bookstore Park Street Hall, Kolkata",
    city: "Kolkata",
    venueType: "physical",
    category: "Community",
    date: "2025-12-08T11:00:00.000Z",
    coverImage: u("photo-1524995997946-a1c029e0a442"),
    agenda: ["11:00 Doors", "13:00 Publisher panel", "16:00 Zine swap", "19:00 Close"],
    speakers: ["Vikram Choudhury", "Little Press Kolkata"],
    faq: [{ question: "Cash?", answer: "Most stalls take UPI; a few zines cash-only." }],
    venueMapUrl: "https://maps.google.com/?q=Park+Street+Kolkata",
    ticketTypes: [{ name: "Entry", price: 99, quantity: 2000 }, { name: "Tote + catalog", price: 349, quantity: 300 }],
  },
  // —— Original + extended upcoming ——
  {
    title: "Hack Night 2026",
    description:
      "A late-night build sprint for students, founders, and makers with live mentors, mini challenges, and a final demo showcase.",
    location: "Bangalore International Centre, Bengaluru",
    city: "Bengaluru",
    venueType: "physical",
    category: "Tech",
    date: "2026-05-01T18:30:00.000Z",
    coverImage: u("photo-1517048676732-d65bc937f952"),
    agenda: ["18:30 - Doors open", "19:00 - Kickoff keynote", "20:30 - Demo showcase"],
    speakers: ["Priya Menon", "Guest Mentor"],
    faq: [{ question: "Is food included?", answer: "Light snacks and coffee are provided." }],
    venueMapUrl: "https://maps.google.com/?q=Bangalore+International+Centre",
    discountCodes: [{ code: "HACK10", type: "percent", value: 10, expiresAt: "2026-04-30" }],
    ticketTypes: [
      { name: "General", price: 499, earlyBirdPrice: 399, earlyBirdEndsAt: "2026-04-25", quantity: 80 },
      { name: "VIP", price: 999, earlyBirdPrice: 799, earlyBirdEndsAt: "2026-04-25", quantity: 25 },
    ],
  },
  {
    title: "City Beats Live",
    description:
      "An open-air indie music evening with food stalls, creator booths, and a high-energy headline set under the city lights.",
    location: "Jio World Garden, Mumbai",
    city: "Mumbai",
    venueType: "physical",
    category: "Music",
    date: "2026-05-10T19:00:00.000Z",
    coverImage: u("photo-1501386761578-eac5c94b800a"),
    agenda: ["19:00 - Gates open", "20:00 - Headline set", "22:00 - Closing"],
    speakers: ["City Beats Ensemble"],
    faq: [{ question: "Are outside cameras allowed?", answer: "Yes, handheld cameras are allowed." }],
    venueMapUrl: "https://maps.google.com/?q=Jio+World+Garden",
    discountCodes: [{ code: "CITY200", type: "amount", value: 200, expiresAt: "2026-05-05" }],
    ticketTypes: [
      { name: "Early Bird", price: 699, earlyBirdPrice: 599, earlyBirdEndsAt: "2026-05-01", quantity: 120 },
      { name: "Lounge", price: 1499, earlyBirdPrice: 1199, earlyBirdEndsAt: "2026-05-01", quantity: 40 },
    ],
  },
  {
    title: "Founder Sprint Summit",
    description:
      "A focused business summit covering pitch practice, fundraising basics, growth experiments, and founder networking.",
    location: "T-Hub, Hyderabad",
    city: "Hyderabad",
    venueType: "physical",
    category: "Business",
    date: "2026-05-18T10:00:00.000Z",
    coverImage: u("photo-1556761175-b413da4baf72"),
    ticketTypes: [
      { name: "Delegate", price: 1299, quantity: 90 },
      { name: "Founder Circle", price: 2499, quantity: 25 },
    ],
  },
  {
    title: "Design Jam Workshop",
    description:
      "A hands-on workshop where participants design a landing page, test it with users, and leave with a polished case-study draft.",
    location: "The Hive, Pune",
    city: "Pune",
    venueType: "physical",
    category: "Workshop",
    date: "2026-05-24T14:00:00.000Z",
    coverImage: u("photo-1522071820081-009f0129c71c"),
    ticketTypes: [
      { name: "Workshop Pass", price: 899, quantity: 60 },
      { name: "Mentor Session", price: 1599, quantity: 15 },
    ],
  },
  {
    title: "Open Source Saturday — Delhi",
    description: "Contributors day: good-first-issues, maintainer office hours, and install-fests for popular Indian OSS projects.",
    location: "NASSCOM 10k Warehouse, Delhi",
    city: "Delhi",
    venueType: "physical",
    category: "Tech",
    date: "2026-06-07T10:00:00.000Z",
    coverImage: u("photo-1531482615713-2afd69097998"),
    agenda: ["10:00 Doors", "10:30 Maintainer intros", "13:00 Lunch", "17:00 Show & tell"],
    speakers: ["CNCF Delhi", "FOSS United"],
    faq: [{ question: "Bring laptop?", answer: "Yes, fully charged; limited power strips." }],
    venueMapUrl: "https://maps.google.com/?q=NASSCOM+Delhi",
    ticketTypes: [{ name: "RSVP", price: 0, quantity: 500 }, { name: "Supporter sticker pack", price: 199, quantity: 100 }],
  },
  {
    title: "Monsoon Jazz & Coffee — Kochi",
    description: "Intimate seated show with Kerala-rooted jazz quartet plus single-origin pour-overs between sets.",
    location: "Brunton Boatyard Courtyard, Kochi",
    city: "Kochi",
    venueType: "physical",
    category: "Music",
    date: "2026-07-19T18:00:00.000Z",
    coverImage: u("photo-1415201364774-f6f0bb35f28f"),
    ticketTypes: [
      { name: "Standard", price: 1299, quantity: 100 },
      { name: "Front row", price: 2199, quantity: 40 },
    ],
  },
  {
    title: "Ahmedabad Startup Grind 2026",
    description: "Fireside with a unicorn PM turned founder, office hours with angels, and a pitch feedback lane.",
    location: "IIM-A New Campus Auditorium",
    city: "Ahmedabad",
    venueType: "physical",
    category: "Business",
    date: "2026-06-21T15:00:00.000Z",
    coverImage: u("photo-1515187029135-18ee286d815b"),
    ticketTypes: [{ name: "Attendee", price: 599, quantity: 350 }, { name: "Office hours", price: 1299, quantity: 40 }],
  },
  {
    title: "Cloud Native Day — Virtual",
    description: "Fully online: Kubernetes, observability, and cost tuning. Live captions and recordings for 30 days.",
    location: "Online — Zoom + Hopin",
    city: "Bengaluru",
    venueType: "online",
    category: "Tech",
    date: "2026-08-02T11:00:00.000Z",
    coverImage: u("photo-1451187580459-43490279c0fa"),
    agenda: ["11:00 Keynote", "12:30 Tracks", "15:00 AMA with platform engineers"],
    faq: [{ question: "Recording?", answer: "Yes, emailed within 48 hours post-event." }],
    venueMapUrl: "https://zoom.us",
    ticketTypes: [{ name: "Live pass", price: 0, quantity: 2000 }, { name: "Recording only", price: 299, quantity: 500 }],
  },
  {
    title: "Chennai Marathon 2026 — Race Day",
    description: "Full, half, and 10K with chip timing, pacers every 10 minutes, and medical tents every 2 km.",
    location: "Marina Beach Start Line, Chennai",
    city: "Chennai",
    venueType: "physical",
    category: "Sports",
    date: "2026-09-06T04:30:00.000Z",
    coverImage: u("photo-1594882645126-1402a5e3fe43"),
    ticketTypes: [
      { name: "10K", price: 1499, earlyBirdPrice: 1199, earlyBirdEndsAt: "2026-07-01", quantity: 4000 },
      { name: "Half", price: 2199, earlyBirdPrice: 1799, earlyBirdEndsAt: "2026-07-01", quantity: 2500 },
      { name: "Full", price: 2799, earlyBirdPrice: 2299, earlyBirdEndsAt: "2026-07-01", quantity: 1200 },
    ],
  },
  {
    title: "Street Art Walk & Auction — Mumbai",
    description: "Curated lane murals, artist talks, and silent auction benefiting public school art labs.",
    location: "Bandra Reclamation Art District",
    city: "Mumbai",
    venueType: "physical",
    category: "Art",
    date: "2026-10-12T16:00:00.000Z",
    coverImage: u("photo-1499781350541-7783eae6a698"),
    ticketTypes: [{ name: "Walk pass", price: 499, quantity: 300 }, { name: "Walk + auction paddle", price: 999, quantity: 80 }],
  },
  {
    title: "North East Folk & Electronic — Shillong (stream)",
    description: "Hybrid: limited in-person passes in Shillong plus HD stream worldwide. Traditional instruments meet modular synths.",
    location: "Police Bazar Open Stage, Shillong",
    city: "Shillong",
    venueType: "online",
    category: "Music",
    date: "2026-11-08T17:30:00.000Z",
    coverImage: u("photo-1511671782779-c97d3d27a1d4"),
    venueMapUrl: "https://youtube.com",
    ticketTypes: [{ name: "Stream", price: 399, quantity: 5000 }, { name: "In-person", price: 899, quantity: 400 }],
  },
  {
    title: "Women in Tech Career Fair 2026",
    description: "Resume clinics, on-site interviews, and allyship workshops. 40 hiring partners across product and eng.",
    location: "Hitex, Hyderabad",
    city: "Hyderabad",
    venueType: "physical",
    category: "Tech",
    date: "2026-09-20T09:00:00.000Z",
    coverImage: u("photo-1573164713714-d95e436ab8d6"),
    ticketTypes: [{ name: "Job seeker", price: 0, quantity: 1200 }, { name: "Recruiter booth", price: 15000, quantity: 40 }],
  },
  {
    title: "Pune Coffee Championships 2026",
    description: "Barista throwdown, cupping for beginners, and roaster market. Free espresso for judges volunteers.",
    location: "West End Mall Rooftop, Pune",
    city: "Pune",
    venueType: "physical",
    category: "Community",
    date: "2026-08-30T11:00:00.000Z",
    coverImage: u("photo-1495474472287-4d71bcdd2085"),
    ticketTypes: [{ name: "Spectator", price: 349, quantity: 400 }, { name: "Cupping workshop", price: 899, quantity: 50 }],
  },
  {
    title: "FinTech Compliance Masterclass",
    description: "KYC, UPI dispute flows, and RBI sandbox walkthrough for PMs and eng leads. CPE credits for company secretaries.",
    location: "WeWork Galaxy, Bengaluru",
    city: "Bengaluru",
    venueType: "physical",
    category: "Business",
    date: "2026-07-11T09:30:00.000Z",
    coverImage: u("photo-1554224155-6726b3ff858f"),
    ticketTypes: [{ name: "Professional", price: 3999, quantity: 100 }, { name: "Startup team (3)", price: 8999, quantity: 25 }],
  },
  {
    title: "Navi Mumbai SaaS Circle 2026",
    description:
      "Monthly PM/engineering dinner: PLG metrics, India pricing, and shipping cadences that do not burn the team.",
    location: "Marriott Navi Mumbai",
    city: "Navi Mumbai",
    venueType: "physical",
    category: "Tech",
    date: "2026-05-29T18:00:00.000Z",
    coverImage: u("photo-1522071820081-009f0129c71c"),
    ticketTypes: [{ name: "Seat", price: 799, quantity: 70 }, { name: "Table (6)", price: 4200, quantity: 8 }],
  },
  {
    title: "Gurgaon Boardgames & Beers 2026",
    description: "Euro games, craft taps, and hosted teach tables — for people who actually finish rulebooks.",
    location: "Sector 29 Social Outdoors, Gurgaon",
    city: "Gurgaon",
    venueType: "physical",
    category: "Community",
    date: "2026-06-15T16:00:00.000Z",
    coverImage: u("photo-1606166188517-3e4ae55b2182"),
    ticketTypes: [{ name: "Board pass", price: 449, quantity: 120 }, { name: "VIP table", price: 2200, quantity: 12 }],
  },
  {
    title: "Surat Startup Stories 2026",
    description: "Founder mic nights, angel office hours, and a bootstrapped-only breakout room.",
    location: "Surat Diamond Bourse Convention Hall",
    city: "Surat",
    venueType: "physical",
    category: "Business",
    date: "2026-07-05T17:30:00.000Z",
    coverImage: u("photo-1556761175-b413da4baf72"),
    ticketTypes: [{ name: "Attendee", price: 399, quantity: 200 }, { name: "Pitch slot", price: 1499, quantity: 20 }],
  },
  {
    title: "Thane Indie Night 2026",
    description: "Warehouse acoustics, two regional openers, and a Mumbai headline under industrial string lights.",
    location: "Thane Creek Studios",
    city: "Thane",
    venueType: "physical",
    category: "Music",
    date: "2026-08-02T19:30:00.000Z",
    coverImage: u("photo-1501386761578-eac5c94b800a"),
    ticketTypes: [
      { name: "Standing", price: 599, earlyBirdPrice: 449, earlyBirdEndsAt: "2026-07-20", quantity: 400 },
      { name: "Balcony", price: 1299, quantity: 80 },
    ],
  },
  {
    title: "Mysuru Heritage Walk & Talk 2026",
    description: "Dawn walk through Devaraja Market, palace stories, and filter coffee with historians.",
    location: "Mysuru Palace North Gate",
    city: "Mysuru",
    venueType: "physical",
    category: "Community",
    date: "2026-07-20T06:00:00.000Z",
    coverImage: u("photo-1587474260584-136574528ed5"),
    ticketTypes: [{ name: "Walk", price: 349, quantity: 80 }, { name: "Walk + breakfast", price: 649, quantity: 40 }],
  },
  {
    title: "Visakhapatnam Beach Run 2026",
    description: "5K/10K on RK Beach road, pacers, and a post-run idli pop-up.",
    location: "RK Beach Start Arch, Visakhapatnam",
    city: "Visakhapatnam",
    venueType: "physical",
    category: "Sports",
    date: "2026-08-17T05:30:00.000Z",
    coverImage: u("photo-1461896836934-ffe607ba8211"),
    ticketTypes: [
      { name: "5K", price: 699, earlyBirdPrice: 549, earlyBirdEndsAt: "2026-07-30", quantity: 1500 },
      { name: "10K", price: 899, earlyBirdPrice: 699, earlyBirdEndsAt: "2026-07-30", quantity: 900 },
    ],
  },
  {
    title: "Indore Photography Walk 2026",
    description: "Golden hour in old bazaars, mentor feedback loops, and a small group exhibit the same weekend.",
    location: "Rajwada Chowk, Indore",
    city: "Indore",
    venueType: "physical",
    category: "Art",
    date: "2026-09-03T17:00:00.000Z",
    coverImage: u("photo-1499781350541-7783eae6a698"),
    ticketTypes: [{ name: "Participant", price: 599, quantity: 35 }, { name: "Rental gear add-on", price: 250, quantity: 15 }],
  },
  {
    title: "Lucknow Ghazal Evening 2026",
    description: "Intimate mehfil, tabla and harmonium forward mix, plus late-night kebab pairings.",
    location: "Hazratganj Cultural Centre",
    city: "Lucknow",
    venueType: "physical",
    category: "Music",
    date: "2026-10-25T19:00:00.000Z",
    coverImage: u("photo-1511671782779-c97d3d27a1d4"),
    ticketTypes: [{ name: "Seated", price: 899, quantity: 200 }, { name: "Front row", price: 1599, quantity: 40 }],
  },
  {
    title: "Ranchi Creator Lab 2026",
    description: "YouTube + podcast studio tours, lighting clinics, and a sponsor-free creator mixer.",
    location: "JSCA International Stadium Complex Annex",
    city: "Ranchi",
    venueType: "physical",
    category: "Workshop",
    date: "2026-06-28T11:00:00.000Z",
    coverImage: u("photo-1531482615713-2afd69097998"),
    ticketTypes: [{ name: "Lab pass", price: 499, quantity: 90 }, { name: "Mentor hour", price: 1299, quantity: 25 }],
  },
];

/** Multiple reviews per past event — eventTitle must match demoEvents.title */
export const bulkReviews = [
  ["Mumbai Audio & Light Expo 2025", 5, "Best trade floor layout I've seen — short walks between booths.", "crowd.aarav@eventwithease.com"],
  ["Mumbai Audio & Light Expo 2025", 4, "Crowded at peak but the line-array demo was worth it.", "crowd.diya@eventwithease.com"],
  ["Mumbai Audio & Light Expo 2025", 5, "Met two suppliers we now use on tour. Solid ROI.", "crowd.kabir@eventwithease.com"],
  ["Delhi Marathon Expo 2025", 5, "Kit pickup was under 8 minutes. Staff knew their stuff.", "crowd.neha@eventwithease.com"],
  ["Delhi Marathon Expo 2025", 4, "Clinic slots ran late but the physio advice was great.", "crowd.vikram@eventwithease.com"],
  ["Hyderabad AI Builders Night 2025", 5, "Midnight hacking with real GPUs — rare in India.", "crowd.ishita@eventwithease.com"],
  ["Hyderabad AI Builders Night 2025", 5, "Talks were dense but well paced. More water stations next time.", "crowd.arjun@eventwithease.com"],
  ["Hyderabad AI Builders Night 2025", 4, "Loved the sticker wall. Wifi hiccup during second block.", "crowd.meera@eventwithease.com"],
  ["Pune Design Weekender 2025", 5, "Portfolio reviews were blunt and useful. Hired two designers from the lounge.", "crowd.sid@eventwithease.com"],
  ["Pune Design Weekender 2025", 5, "Student ticket was a steal. Figma templates alone paid for it.", "crowd.tara@eventwithease.com"],
  ["Chennai Indie Film Showcase 2025", 4, "Subtitles were crisp. Wish Block B had one more short.", "crowd.karan@eventwithease.com"],
  ["Chennai Indie Film Showcase 2025", 5, "Q&A with directors felt intimate. Great curation.", "crowd.ananya@eventwithease.com"],
  ["Goa Beach Startup Brunch 2025", 5, "Investor rotations were timed perfectly — no awkward hovering.", "crowd.dev@eventwithease.com"],
  ["Goa Beach Startup Brunch 2025", 4, "Sun was brutal — maybe more shade next year.", "crowd.priya@eventwithease.com"],
  ["Kolkata Winter Street Food Fest 2025", 5, "RFID wallet made lines fly. Family zone was clean.", "crowd.yash@eventwithease.com"],
  ["Kolkata Winter Street Food Fest 2025", 5, "Chef throwdown was the highlight. Come hungry.", "crowd.meera@eventwithease.com"],
  ["Bengaluru Product Leadership Summit 2025", 5, "NDA room conversations were gold. Chatham rules respected.", "crowd.diya@eventwithease.com"],
  ["Bengaluru Product Leadership Summit 2025", 4, "Pricey but the peer group was senior as promised.", "crowd.kabir@eventwithease.com"],
  ["Mumbai Audio & Light Expo 2025", 4, "Load-in lanes were tight for trucks — plan extra time.", "crowd.vikram@eventwithease.com"],
  ["Delhi Marathon Expo 2025", 5, "Volunteers everywhere — felt very safe for families.", "crowd.ishita@eventwithease.com"],
  ["Pune Design Weekender 2025", 4, "WiFi struggled during afternoon sessions.", "crowd.arjun@eventwithease.com"],
  ["Chennai Indie Film Showcase 2025", 5, "Projection quality was cinema-grade.", "crowd.priya@eventwithease.com"],
  ["Goa Beach Startup Brunch 2025", 5, "Met our lead investor here. Forever grateful.", "crowd.sid@eventwithease.com"],
  ["Mumbai Audio & Light Expo 2025", 5, "Demo rooms were sound-treated — you could actually hear the difference.", "crowd.neha@eventwithease.com"],
  ["Mumbai Audio & Light Expo 2025", 4, "Parking was tight; arrive early or cab it.", "crowd.ishita@eventwithease.com"],
  ["Delhi Marathon Expo 2025", 5, "Bag check was fast; loved the pace zones map.", "crowd.arjun@eventwithease.com"],
  ["Delhi Marathon Expo 2025", 4, "Merch queue was long Saturday noon.", "crowd.meera@eventwithease.com"],
  ["Hyderabad AI Builders Night 2025", 5, "Sponsor swag was tasteful, not junk.", "crowd.tara@eventwithease.com"],
  ["Pune Design Weekender 2025", 5, "Typography workshop alone was worth the ticket.", "crowd.ananya@eventwithease.com"],
  ["Chennai Indie Film Showcase 2025", 4, "Great AC in Screen 1; concessions pricey.", "crowd.dev@eventwithease.com"],
  ["Goa Beach Startup Brunch 2025", 5, "Pitch timers were strict — good discipline.", "crowd.yash@eventwithease.com"],
  ["Kolkata Winter Street Food Fest 2025", 4, "Vegetarian row was a bit hidden — better signage please.", "crowd.priya@eventwithease.com"],
  ["Bengaluru Product Leadership Summit 2025", 5, "Roundtables had printed prompts — kept conversations on rails.", "crowd.aarav@eventwithease.com"],
  ["Hyderabad AI Builders Night 2025", 4, "Would love a printed run-of-show next time.", "crowd.sid@eventwithease.com"],
  ["Chennai Indie Film Showcase 2025", 5, "Loved the regional shorts block.", "crowd.tara@eventwithease.com"],
  ["Kolkata Winter Street Food Fest 2025", 5, "Kids’ corner was staffed — parents could actually eat.", "crowd.ishita@eventwithease.com"],
  ["Pune Design Weekender 2025", 4, "Coffee ran out between sessions — minor fix.", "crowd.neha@eventwithease.com"],
  ["Bengaluru Writers Salon 2025", 5, "Intimate room — heard every word.", "crowd.aarav@eventwithease.com"],
  ["Bengaluru Writers Salon 2025", 4, "Would love a winter edition too.", "crowd.diya@eventwithease.com"],
  ["Mumbai Comedy Store Night 2025", 5, "Headliner was worth twice the ticket.", "crowd.kabir@eventwithease.com"],
  ["Mumbai Comedy Store Night 2025", 4, "Room gets warm — dress light.", "crowd.neha@eventwithease.com"],
  ["Hyderabad Design Critique 2025", 5, "Reviewers were direct but kind. Grew a ton in one afternoon.", "crowd.ishita@eventwithease.com"],
  ["Hyderabad Design Critique 2025", 5, "Rotations kept on schedule — rare.", "crowd.arjun@eventwithease.com"],
  ["Kochi Sunsets Acoustic 2025", 5, "Sound on the roof was surprisingly clean.", "crowd.meera@eventwithease.com"],
  ["Kochi Sunsets Acoustic 2025", 4, "Wish there were more low seats.", "crowd.sid@eventwithease.com"],
  ["Jaipur Photo Walk 2025", 5, "Mentor feedback between blocks was gold.", "crowd.tara@eventwithease.com"],
  ["Jaipur Photo Walk 2025", 5, "Golden hour timing was perfect.", "crowd.ananya@eventwithease.com"],
  ["Kolkata Indie Book Fair 2025", 5, "Zine swap corner was my highlight.", "crowd.dev@eventwithease.com"],
  ["Kolkata Indie Book Fair 2025", 4, "Hall was crowded Saturday noon.", "crowd.priya@eventwithease.com"],
];

/** Private feedback for organiser dashboard — past events */
export const bulkFeedback = [
  ["Mumbai Audio & Light Expo 2025", 5, "Please publish speaker decks — we will cite you.", "crowd.aarav@eventwithease.com"],
  ["Delhi Marathon Expo 2025", 4, "Signage to clinics could be bigger.", "crowd.neha@eventwithease.com"],
  ["Hyderabad AI Builders Night 2025", 5, "More power strips in hack corner.", "crowd.dev@eventwithease.com"],
  ["Pune Design Weekender 2025", 5, "Loved the hiring lounge — maybe add 15 min 1:1 slots.", "crowd.sid@eventwithease.com"],
  ["Chennai Indie Film Showcase 2025", 4, "AC was cold in Screen 2.", "crowd.karan@eventwithease.com"],
  ["Goa Beach Startup Brunch 2025", 5, "Perfect length. Not a minute of fluff.", "crowd.diya@eventwithease.com"],
  ["Kolkata Winter Street Food Fest 2025", 5, "Stall map in the app was accurate — rare!", "crowd.yash@eventwithease.com"],
  ["Bengaluru Product Leadership Summit 2025", 5, "Coffee ran out at 4pm — otherwise flawless.", "crowd.kabir@eventwithease.com"],
  ["Bengaluru Writers Salon 2025", 5, "Please publish the reader list next time — great discovery.", "crowd.aarav@eventwithease.com"],
  ["Hyderabad Design Critique 2025", 5, "More power strips in review corners would help.", "crowd.dev@eventwithease.com"],
  ["Kochi Sunsets Acoustic 2025", 4, "Balcony sightlines were tight for tall folks.", "crowd.neha@eventwithease.com"],
];

/**
 * Booking seeds: eventTitle, attendeeEmail, ticketTypeName, quantity, checkedIn (boolean)
 */
export const bookingSeeds = [
  ["Hack Night 2026", "demo.attendee@eventwithease.com", "General", 2, true],
  ["Hack Night 2026", "crowd.aarav@eventwithease.com", "VIP", 1, false],
  ["City Beats Live", "crowd.diya@eventwithease.com", "Early Bird", 2, false],
  ["City Beats Live", "crowd.kabir@eventwithease.com", "Lounge", 1, true],
  ["Founder Sprint Summit", "crowd.neha@eventwithease.com", "Delegate", 1, false],
  ["Monsoon Jazz & Coffee — Kochi", "crowd.ishita@eventwithease.com", "Standard", 1, false],
  ["Open Source Saturday — Delhi", "crowd.arjun@eventwithease.com", "RSVP", 1, false],
  ["Chennai Marathon 2026 — Race Day", "crowd.meera@eventwithease.com", "10K", 1, false],
  ["Chennai Marathon 2026 — Race Day", "crowd.sid@eventwithease.com", "Half", 2, false],
  ["FinTech Compliance Masterclass", "crowd.tara@eventwithease.com", "Professional", 1, false],
  ["Women in Tech Career Fair 2026", "crowd.ananya@eventwithease.com", "Job seeker", 1, false],
  ["Cloud Native Day — Virtual", "crowd.dev@eventwithease.com", "Live pass", 1, false],
  ["Street Art Walk & Auction — Mumbai", "crowd.priya@eventwithease.com", "Walk pass", 3, false],
  ["Pune Coffee Championships 2026", "crowd.yash@eventwithease.com", "Spectator", 2, false],
  ["Ahmedabad Startup Grind 2026", "crowd.karan@eventwithease.com", "Attendee", 1, true],
];

/** Additional demo hosts — real-style individual names (seed creates accounts). */
export const extraDemoHosts = [
  {
    name: "Rahul Iyer",
    email: "rahul.iyer@eventwithease.com",
    password: "demo1234",
    role: "organiser",
    roles: ["organiser", "attendee"],
    hostTagline: "Live culture · music, comedy & night experiences · Mumbai",
    hostBio:
      "Rahul curates live rooms and open-air culture nights—tight line-ups, fair artist splits, and audiences who actually show up on time.",
    linkedinUrl: "https://linkedin.com/in/example-rahul-iyer",
    twitterUrl: "https://x.com",
    instagramUrl: "https://instagram.com",
    websiteUrl: "https://eventwithease.com",
  },
  {
    name: "Simran Khanna",
    email: "simran.khanna@eventwithease.com",
    password: "demo1234",
    role: "organiser",
    roles: ["organiser", "attendee"],
    hostTagline: "Tech & design communities · Hyderabad & remote",
    hostBio:
      "Simran runs builder nights, OSS days, and critique-first design meetups—fewer slides, more shipping and honest feedback.",
    linkedinUrl: "https://linkedin.com/in/example-simran-khanna",
    twitterUrl: "https://x.com",
    instagramUrl: "https://instagram.com",
    websiteUrl: "https://eventwithease.com",
  },
  {
    name: "Vikram Choudhury",
    email: "vikram.choudhury@eventwithease.com",
    password: "demo1234",
    role: "organiser",
    roles: ["organiser", "attendee"],
    hostTagline: "Design weeks, indie publishing & creative weekends",
    hostBio:
      "Vikram programmes multi-day design and arts weekends with small cohorts, clear schedules, and space for real portfolio work.",
    linkedinUrl: "https://linkedin.com/in/example-vikram-choudhury",
    twitterUrl: "https://x.com",
    instagramUrl: "https://instagram.com",
    websiteUrl: "https://eventwithease.com",
  },
  {
    name: "Meera Patel",
    email: "meera.patel@eventwithease.com",
    password: "demo1234",
    role: "organiser",
    roles: ["organiser", "attendee"],
    hostTagline: "South India stages · intimate music & film",
    hostBio:
      "Meera books acoustic rooms, hybrid streams, and film-forward evenings where sound quality and respectful crowds come first.",
    linkedinUrl: "https://linkedin.com/in/example-meera-patel",
    twitterUrl: "https://x.com",
    instagramUrl: "https://instagram.com",
    websiteUrl: "https://eventwithease.com",
  },
  {
    name: "Arjun Natesan",
    email: "arjun.natesan@eventwithease.com",
    password: "demo1234",
    role: "organiser",
    roles: ["organiser", "attendee"],
    hostTagline: "Founder circles, runs & weekend field trips",
    hostBio:
      "Arjun hosts founder brunches, angel office hours, and movement-forward weekends—always with clear agendas and on-time transitions.",
    linkedinUrl: "https://linkedin.com/in/example-arjun-natesan",
    twitterUrl: "https://x.com",
    instagramUrl: "https://instagram.com",
    websiteUrl: "https://eventwithease.com",
  },
];

/** Seed sets cancelledAt on this title (notification + booking-closed demo). */
export const demoCancelledEventTitle = "Design Jam Workshop";
export const demoCancelledEventAt = "2026-04-10T08:00:00.000Z";

/**
 * Every listed event is assigned to a host so Discover shows varied names.
 * Emails: demo.organiser@ (Priya), rahul.iyer@, simran.khanna@, vikram.choudhury@, meera.patel@, arjun.natesan@
 * Titles not listed fall back to demo organiser in seed.
 */
export const eventHostEmailByTitle = {
  // Priya Menon
  "Mumbai Audio & Light Expo 2025": "demo.organiser@eventwithease.com",
  "Kolkata Winter Street Food Fest 2025": "demo.organiser@eventwithease.com",
  "Hack Night 2026": "demo.organiser@eventwithease.com",
  "Cloud Native Day — Virtual": "demo.organiser@eventwithease.com",
  "FinTech Compliance Masterclass": "demo.organiser@eventwithease.com",
  "Navi Mumbai SaaS Circle 2026": "demo.organiser@eventwithease.com",
  "Bengaluru Writers Salon 2025": "demo.organiser@eventwithease.com",

  // Rahul Iyer
  "Delhi Marathon Expo 2025": "rahul.iyer@eventwithease.com",
  "Bengaluru Product Leadership Summit 2025": "rahul.iyer@eventwithease.com",
  "City Beats Live": "rahul.iyer@eventwithease.com",
  "Thane Indie Night 2026": "rahul.iyer@eventwithease.com",
  "Street Art Walk & Auction — Mumbai": "rahul.iyer@eventwithease.com",
  "Lucknow Ghazal Evening 2026": "rahul.iyer@eventwithease.com",
  "Mumbai Comedy Store Night 2025": "rahul.iyer@eventwithease.com",

  // Simran Khanna
  "Hyderabad AI Builders Night 2025": "simran.khanna@eventwithease.com",
  "Founder Sprint Summit": "simran.khanna@eventwithease.com",
  "Women in Tech Career Fair 2026": "simran.khanna@eventwithease.com",
  "Ranchi Creator Lab 2026": "simran.khanna@eventwithease.com",
  "Open Source Saturday — Delhi": "simran.khanna@eventwithease.com",
  "Hyderabad Design Critique 2025": "simran.khanna@eventwithease.com",

  // Vikram Choudhury
  "Pune Design Weekender 2025": "vikram.choudhury@eventwithease.com",
  "Design Jam Workshop": "vikram.choudhury@eventwithease.com",
  "Pune Coffee Championships 2026": "vikram.choudhury@eventwithease.com",
  "Indore Photography Walk 2026": "vikram.choudhury@eventwithease.com",
  "Kolkata Indie Book Fair 2025": "vikram.choudhury@eventwithease.com",

  // Meera Patel
  "Chennai Indie Film Showcase 2025": "meera.patel@eventwithease.com",
  "Monsoon Jazz & Coffee — Kochi": "meera.patel@eventwithease.com",
  "Chennai Marathon 2026 — Race Day": "meera.patel@eventwithease.com",
  "Mysuru Heritage Walk & Talk 2026": "meera.patel@eventwithease.com",
  "North East Folk & Electronic — Shillong (stream)": "meera.patel@eventwithease.com",
  "Kochi Sunsets Acoustic 2025": "meera.patel@eventwithease.com",

  // Arjun Natesan
  "Goa Beach Startup Brunch 2025": "arjun.natesan@eventwithease.com",
  "Ahmedabad Startup Grind 2026": "arjun.natesan@eventwithease.com",
  "Gurgaon Boardgames & Beers 2026": "arjun.natesan@eventwithease.com",
  "Visakhapatnam Beach Run 2026": "arjun.natesan@eventwithease.com",
  "Surat Startup Stories 2026": "arjun.natesan@eventwithease.com",
  "Jaipur Photo Walk 2025": "arjun.natesan@eventwithease.com",
};
